openapi: 3.0.3
info:
  title: ITindr Api
  description: "Base URL: http://193.38.50.175/itindr/api/mobile"
  version: 1.0.0
  contact:
    email: shkipper65@gmail.com
    name: ShkiTTer
servers:
  - url: '/itindr/api/mobile'

tags:
  - name: Auth
  - name: Profile
  - name: Topic
  - name: User

paths:
  /v1/auth/login:
    description: 'Authorization'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginBody'
            example:
              email: 'test@mail.ru'
              password: 'qwerty'

      responses:
        200:
          $ref: '#/components/responses/TokenInfo'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
      tags:
        - Auth

  /v1/auth/register:
    description: 'Registration'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterBody'
            example:
              email: 'test@mail.ru'
              password: 'qwerty'

      responses:
        200:
          $ref: '#/components/responses/TokenInfo'
        400:
          $ref: '#/components/responses/BadRequest'
        409:
          $ref: '#/components/responses/Conflict'
        500:
          $ref: '#/components/responses/InternalServerError'
      tags:
        - Auth

  /v1/auth/logout:
    description: 'Sign out of your account'
    post:
      security:
        - BearerAuth: [ ]
      responses:
        204:
          description: 'Logout succeeded'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
      tags:
        - Auth

  /v1/auth/refresh:
    description: 'Refreshing Access token with Refresh token'
    post:
      security:
        - BearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenBody'
            example:
              refreshToken: 'a3dWTmJDQkVuQlNHNGRvWU9LZW4='
      responses:
        200:
          $ref: '#/components/responses/TokenInfo'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
      tags:
        - Auth

  /v1/profile:
    get:
      description: 'Retrieving User Profile Information'
      security:
        - BearerAuth: [ ]
      responses:
        200:
          $ref: '#/components/responses/ProfileWithTopics'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
      tags:
        - Profile

    patch:
      description: 'Updating user profile'
      security:
        - BearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfileBody'
            example:
              name: 'Иван'
              aboutMyself: null
              topics: [ 'b214f7d1-6962-4efa-8b7f-36fa5d3db104', 'eeb0034b-bc65-407e-a665-b4bfeb980152' ]
      responses:
        200:
          $ref: '#/components/responses/ProfileWithTopics'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
      tags:
        - Profile

  /v1/profile/avatar:
    post:
      description: 'Uploading user avatar'
      security:
        - BearerAuth: [ ]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
              required:
                - avatar
      responses:
        204:
          description: 'Avatar uploaded successfully'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
      tags:
        - Profile

  /v1/topic:
    get:
      description: 'Getting a list of all topics'
      security:
        - BearerAuth: [ ]
      responses:
        200:
          $ref: '#/components/responses/TopicInfoList'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
      tags:
        - Topic

  /v1/user/feed:
    get:
      description: 'Getting a list of users who may be of interest to you'
      security:
        - BearerAuth: [ ]
      responses:
        200:
          $ref: '#/components/responses/ProfileWithTopicList'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
      tags:
        - User

  /v1/user/{userId}/like:
    description: 'Set like for user'
    post:
      security:
        - BearerAuth: [ ]
      responses:
        200:
          $ref: '#/components/responses/LikeResult'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          $ref: '#/components/responses/Conflict'
        500:
          $ref: '#/components/responses/InternalServerError'
      tags:
        - User

  /v1/user/{userId}/dislike:
    description: 'Set dislike for user'
    post:
      security:
        - BearerAuth: [ ]
      responses:
        204:
          description: 'Dislike successfully posted'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          $ref: '#/components/responses/Conflict'
        500:
          $ref: '#/components/responses/InternalServerError'
      tags:
        - User

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LoginBody:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minimum: 8
      required:
        - email
        - password

    RegisterBody:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minimum: 8
      required:
        - email
        - password

    RefreshTokenBody:
      type: object
      properties:
        refreshToken:
          type: string
      required:
        - refreshToken

    UpdateProfileBody:
      type: object
      properties:
        name:
          type: string
        aboutMyself:
          type: string
        topics:
          type: array
          items:
            type: string
            format: uuid
      required:
        - name

  responses:
    BadRequest:
      description: 'Bad Request Error'
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
          example:
            message: 'Bad Request'

    NotFound:
      description: 'Not Found Error'
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
          example:
            message: 'Resource not found'

    Unauthorized:
      description: 'Unauthorized Error'
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
          example:
            message: 'You are not authorized'

    Forbidden:
      description: 'Forbidden Error'
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
          example:
            message: 'Not enough rights to perform the action'

    Conflict:
      description: 'Conflict Error'
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
          example:
            message: 'Resource already exist'

    InternalServerError:
      description: 'Internal Server Error'
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
          example:
            message: 'Something went wrong'

    TokenInfo:
      description: 'Token information'
      content:
        application/json:
          schema:
            type: object
            properties:
              accessToken:
                type: string
              accessTokenExpiredAt:
                type: integer
                format: int64
              refreshToken:
                type: string
              refreshTokenExpiredAt:
                type: integer
                format: int64
            required:
              - accessToken
              - accessTokenExpiredAt
              - refreshToken
              - refreshTokenExpiredAt
          example:
            accessToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'
            accessTokenExpiredAt: 1632325306
            refreshToken: 'a3dWTmJDQkVuQlNHNGRvWU9LZW4='
            refreshTokenExpiredAt: 1632325306

    ProfileWithTopics:
      description: 'Profile info with topics'
      content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                type: string
                format: uuid
              name:
                type: string
              aboutMyself:
                type: string
              avatar:
                type: string
                format: url
              topics:
                type: array
                items:
                  $ref: '#/components/responses/TopicInfo'
            required:
              - name
              - topics
            example:
              userId: 'b214f7d1-6962-4efa-8b7f-36fa5d3db104'
              name: 'Иван'
              aboutMyself: null
              avatar: null
              topics:
                - id: 'b214f7d1-6962-4efa-8b7f-36fa5d3db104'
                  title: 'Kotlin'
                - id: 'b214f7d1-6962-4efa-8b7f-36fa5d3db104'
                  title: 'Ktor'

    ProfileWithTopicList:
      description: 'User profile list'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/responses/ProfileWithTopics'
            example:
              - userId: 'b214f7d1-6962-4efa-8b7f-36fa5d3db104'
                name: 'Иван'
                aboutMyself: null
                avatar: null
                topics:
                  - id: 'b214f7d1-6962-4efa-8b7f-36fa5d3db104'
                    title: 'Kotlin'
                  - id: 'b214f7d1-6962-4efa-8b7f-36fa5d3db104'
                    title: 'Ktor'
              - userId: 'b214f7d1-6962-4efa-8b7f-36fa5d3db104'
                name: 'Иван'
                aboutMyself: null
                avatar: null
                topics:
                  - id: 'b214f7d1-6962-4efa-8b7f-36fa5d3db104'
                    title: 'Kotlin'
                  - id: 'b214f7d1-6962-4efa-8b7f-36fa5d3db104'
                    title: 'Ktor'

    TopicInfo:
      description: 'Info about topic'
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
                format: uuid
              title:
                type: string
            required:
              - id
              - title
            example:
              id: 'b214f7d1-6962-4efa-8b7f-36fa5d3db104'
              title: 'Kotlin'

    TopicInfoList:
      description: 'List of topics'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/responses/TopicInfo'
            example:
              - id: 'b214f7d1-6962-4efa-8b7f-36fa5d3db104'
                title: 'Kotlin'
              - id: 'b214f7d1-6962-4efa-8b7f-36fa5d3db104'
                title: 'Ktor'

    LikeResult:
      description: 'Result of like user'
      content:
        application/json:
          schema:
            type: object
            properties:
              isMutual:
                type: boolean
                example: true